[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[lib]
name = "read"
path = "src/util/rust/read.rs"

[[bin]]
name = "calorie_counting"
path = "src/twentytwentytwo/one/calorie_counting.rs"
