[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[lib]
name = "util"
path = "src/util/rust/lib.rs"

[[bin]]
name = "calorie_counting"
path = "src/twentytwentytwo/one/calorie_counting.rs"

[[bin]]
name = "rock_paper_scissors"
path = "src/twentytwentytwo/two/rock_paper_scissors.rs"

[[bin]]
name = "rucksack_reorganization"
path = "src/twentytwentytwo/three/rucksack_reorganization.rs"
