name: advent-of-code
version: 0.1.0.0
author: Cael Warner
copyright: 2024 Cael Warner

dependencies:
  - base >= 4.7 && < 5
  - extra
  - containers
  - multiset
  - clock
  - deepseq
  - megaparsec

shared-executable-dependencies: &shared-deps
  - advent-of-code

ghc-options:
  -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wmissing-export-lists
  -Wmissing-home-modules
  -Wpartial-fields
  -Wredundant-constraints

library:
  source-dirs: src/util/haskell

executables:
  historian-hysteria:
    main: HistorianHysteria.hs
    source-dirs: src/twentytwentyfour/one
    dependencies: *shared-deps
  red-nosed-reindeer:
    main: RedNosedReindeer.hs
    source-dirs: src/twentytwentyfour/two
    dependencies: *shared-deps
  mull-it-over:
    main: MullItOver.hs
    source-dirs: src/twentytwentyfour/three
    dependencies: *shared-deps
  ceres-search:
    main: CeresSearch.hs
    source-dirs: src/twentytwentyfour/four
    dependencies: *shared-deps