name: advent-of-code
version: 0.1.0.0
author: Cael Warner
copyright: 2024 Cael Warner

dependencies:
  - base >= 4.7 && < 5
  - extra
  - containers
  - multiset
  - clock
  - deepseq
  - megaparsec
  - array

shared-executable-dependencies: &shared-deps
  - advent-of-code

ghc-options:
  -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wmissing-export-lists
  -Wmissing-home-modules
  -Wpartial-fields
  -Wredundant-constraints

library:
  source-dirs: src/util/haskell

executables:
  historian-hysteria:
    main: HistorianHysteria.hs
    source-dirs: src/twentytwentyfour/one
    dependencies: *shared-deps
  red-nosed-reindeer:
    main: RedNosedReindeer.hs
    source-dirs: src/twentytwentyfour/two
    dependencies: *shared-deps
  mull-it-over:
    main: MullItOver.hs
    source-dirs: src/twentytwentyfour/three
    dependencies: *shared-deps
  ceres-search:
    main: CeresSearch.hs
    source-dirs: src/twentytwentyfour/four
    dependencies: *shared-deps
  print-queue:
    main: PrintQueue.hs
    source-dirs: src/twentytwentyfour/five
    dependencies: *shared-deps
  guard-gallivant:
    main: GuardGallivant.hs
    source-dirs: src/twentytwentyfour/six
    dependencies: *shared-deps
  bridge-repair:
    main: BridgeRepair.hs
    source-dirs: src/twentytwentyfour/seven
    dependencies: *shared-deps
  resonant-collinearity:
    main: ResonantCollinearity.hs
    source-dirs: src/twentytwentyfour/eight
    dependencies: *shared-deps
  disk-fragmenter:
    main: DiskFragmenter.hs
    source-dirs: src/twentytwentyfour/nine
    dependencies: *shared-deps